# Generated by Django 3.1.6 on 2021-02-17 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('neotuber', 'subscriber')},
        ),
    ]
