# Generated by Django 3.1.6 on 2021-02-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_socialloginuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialloginuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialloginuser',
            name='social_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
