# Generated by Django 3.1.6 on 2021-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210223_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialloginuser',
            name='social_id',
        ),
        migrations.AddField(
            model_name='socialloginuser',
            name='social',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
