# Generated by Django 3.1.6 on 2021-02-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210224_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialloginuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
